#!/bin/bash

echo "[INFO] Check version conflicts in extraction-framework and distributed-extraction-framework"
mkdir tmp;
cd tmp;

# Put values in a table for columnar list view
touch table.txt;
echo "================================" "============" >> table.txt
echo "Framework" "Version" >> table.txt
echo "================================" "============" >> table.txt

# Get the pom file for extraction framework and rename it
wget https://raw.githubusercontent.com/dbpedia/extraction-framework/master/pom.xml;
mv pom.xml extraction_framework_pom;

# Get the pom file for distributed extraction framework and rename it
wget https://raw.githubusercontent.com/dbpedia/distributed-extraction-framework/master/pom.xml
mv pom.xml distributed_extraction_framework_pom;

# Get build version using sed
var1=`cat extraction_framework_pom | grep SNAPSHOT | sed 's|<[^>]*>||g'`

# Remove leading spaces using tr command and append to the table file
var1_no_lead_space="$(echo -e "${var1}" | tr -d '[[:space:]]')"
echo "Extraction-framework" $var1_no_lead_space >> table.txt;

# Get build version for distribution extraction framework using sed
var2=`cat distributed_extraction_framework_pom | grep SNAPSHOT | sed 's|<[^>]*>||g'`

# Remove leading spaces using tr command and append to the table file
var2_no_lead_space="$(echo -e "${var2}" | tr -d '[[:space:]]')"
echo "Distributed-extraction-framework" $var2_no_lead_space >> table.txt;
echo "================================" "============" >> table.txt

# Display table using column command
column -t -s' ' table.txt;
echo ""

if [ "$var1_no_lead_space" == "$var2_no_lead_space" ]
then
	echo "[INFO] Matching versions found"
else
	echo "[INFO] Version mismatch found"
fi
# Delete the temp directory
cd ..;
rm -rf tmp;

download_file_diff=`diff ../config/download/download.properties ../config/download/download.properties.template | wc -l`;
if [[ $download_file_diff -eq 0 ]]; then
	echo "[INFO] download.properties file not changed"
else
	echo "[INFO] download.properties file has been modified by the user at " $download_file_diff " places"
fi

dist_download_file_diff=`diff ../config/download/dist-download.properties ../config/download/dist-download.properties.template | wc -l`;
if [[ $dist_download_file_diff -eq 0 ]]; then
	echo "[INFO] download.properties file not changed"
else
	echo "[INFO] download.properties file has been modified by the user at " $dist_download_file_diff " places"
fi

extraction_file_diff=`diff ../config/extraction/config.properties ../config/extraction/config.properties.template | wc -l`;
if [[ $extraction_file_diff -eq 0 ]]; then
	echo "[INFO] config.properties file not changed"
else
	echo "[INFO] config.properties file has been modified by the user at " $extraction_file_diff " places"
fi

dist_extraction_file_diff=`diff ../config/extraction/dist-config.properties ../config/extraction/dist-config.properties.template | wc -l`;
if [[ $dist_extraction_file_diff -eq 0 ]]; then
	echo "[INFO] dist-config.properties file not changed"
else
	echo "[INFO] dist-config.properties file has been modified by the user at " $dist_extraction_file_diff " places"
fi
